### ISSUE TITLE
Initial checklist

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/CitableXML.jl#1]
Functions we need:

- [ ] parse an XPath template
- [ ] use an XPath template to select nodes and form URNs
- [ ] serialize a parsed node back to XML equivalent to source XML
- [ ] recursively collect text content from an element
